/**
 * Central export for all shared types
 */

// Settings types
export type {
  ChannelId,
  VideoId,
  CustomDomainId,
  ShortVideoPlatform,
  FullSitePlatform,
  SNSPlatform,
  Platform,
  ShortVideoPlatformSettings,
  FullSitePlatformSettings,
  SNSPlatformSettings,
  PlatformSettings,
  CustomBlockedDomain,
  DayOfWeek,
  TimeRange,
  ScheduleConfig,
  BlockPageTheme,
  BlockPageSettings,
  FocusDuration,
  FocusModeSettings,
  FocusModeState,
  PomodoroMode,
  PomodoroSettings,
  PomodoroState,
  SiteTimeLimit,
  SiteTimeUsage,
  TimeLimitsSettings,
  TimeLimitsState,
  DailyTimeRecord,
  TimeTrackingSettings,
  TimeTrackingState,
  StreakSettings,
  StreakData,
  ChallengeDifficulty,
  ChallengeType,
  ChallengeSettings,
  ChallengeData,
  ChallengeState,
  LockdownSettings,
  LockdownState,
  BlockingStats,
  UserPreferences,
  PopupView,
  SupportedLanguage,
  Settings,
  SettingsUpdate,
  // CommitmentLock types (re-exported from settings.ts)
  CommitmentLockSettings,
  CommitmentLockState,
  CommitmentLockLevel,
  UnlockAttempt,
  UnlockHistory,
  UnlockCheckResult,
  UnlockFlowStep,
  UnlockFlowState,
  UnlockFailureReason,
  PremiumState,
  PremiumFeature,
  CommitmentLockStats,
} from './settings';

export { isValidSettings, isValidCustomBlockedDomain } from './settings';

// Rules types
export type {
  DetectionMethod,
  BlockingAction,
  UrlRule,
  SelectorRule,
  AttributeRule,
  BlockingRule,
  PlatformRules,
  CustomRule,
} from './rules';

export { isValidBlockingRule } from './rules';

// Log types
export type { LogLevel, AppLogEntry } from './logs';

// Message types
export type {
  MessageType,
  Message,
  GetSettingsMessage,
  UpdateSettingsMessage,
  GetStatsMessage,
  LogBlockMessage,
  PingMessage,
  FocusStartMessage,
  FocusCancelMessage,
  FocusGetStateMessage,
  FocusExtendMessage,
  PomodoroStartMessage,
  PomodoroPauseMessage,
  PomodoroResumeMessage,
  PomodoroStopMessage,
  PomodoroSkipMessage,
  PomodoroGetStateMessage,
  TimeTrackActivityMessage,
  TimeGetUsageMessage,
  TimeResetUsageMessage,
  TimeCheckLimitMessage,
  TimeGetHistoryMessage,
  TimeClearHistoryMessage,
  StreakGetDataMessage,
  StreakResetMessage,
  StreakCheckDayMessage,
  ChallengeRequestMessage,
  ChallengeSubmitMessage,
  ChallengeGetStateMessage,
  LockdownSetPinMessage,
  LockdownVerifyPinMessage,
  LockdownActivateMessage,
  LockdownDeactivateMessage,
  LockdownGetStateMessage,
  LockdownRequestEmergencyBypassMessage,
  LockdownCheckEmergencyBypassMessage,
  // Commitment Lock messages
  CommitmentLockGetStateMessage,
  CommitmentLockCheckUnlockMessage,
  CommitmentLockStartUnlockMessage,
  CommitmentLockSubmitIntentionMessage,
  CommitmentLockRequestChallengeMessage,
  CommitmentLockSubmitChallengeMessage,
  CommitmentLockConfirmUnlockMessage,
  CommitmentLockCancelUnlockMessage,
  CommitmentLockGetHistoryMessage,
  CommitmentLockGetStatsMessage,
  CommitmentLockResetStateMessage,
  // Premium messages
  PremiumGetStateMessage,
  PremiumCheckFeatureMessage,
  MessageResponse,
  GetSettingsResponse,
  UpdateSettingsResponse,
  GetStatsResponse,
  LogBlockResponse,
  PingResponse,
  FocusStartResponse,
  FocusCancelResponse,
  FocusGetStateResponse,
  FocusExtendResponse,
  PomodoroStartResponse,
  PomodoroPauseResponse,
  PomodoroResumeResponse,
  PomodoroStopResponse,
  PomodoroSkipResponse,
  PomodoroGetStateResponse,
  TimeTrackActivityResponse,
  TimeGetUsageResponse,
  TimeResetUsageResponse,
  TimeCheckLimitResult,
  TimeCheckLimitResponse,
  TimeGetHistoryResponse,
  TimeClearHistoryResponse,
  StreakGetDataResponse,
  StreakResetResponse,
  StreakCheckDayResponse,
  ChallengeSubmitResult,
  ChallengeRequestResponse,
  ChallengeSubmitResponse,
  ChallengeGetStateResponse,
  LockdownVerifyPinResult,
  EmergencyBypassCheckResult,
  LockdownSetPinResponse,
  LockdownVerifyPinResponse,
  LockdownActivateResponse,
  LockdownDeactivateResponse,
  LockdownGetStateResponse,
  LockdownRequestEmergencyBypassResponse,
  LockdownCheckEmergencyBypassResponse,
  // Commitment Lock responses
  CommitmentLockUnlockFlowResult,
  CommitmentLockChallengeResult,
  PremiumFeatureCheckResult,
  CommitmentLockGetStateResponse,
  CommitmentLockCheckUnlockResponse,
  CommitmentLockStartUnlockResponse,
  CommitmentLockSubmitIntentionResponse,
  CommitmentLockRequestChallengeResponse,
  CommitmentLockSubmitChallengeResponse,
  CommitmentLockConfirmUnlockResponse,
  CommitmentLockCancelUnlockResponse,
  CommitmentLockGetHistoryResponse,
  CommitmentLockGetStatsResponse,
  CommitmentLockResetStateResponse,
  // Premium responses
  PremiumGetStateResponse,
  PremiumCheckFeatureResponse,
  // adalab study integration
  AdalabPhase,
  AdalabSyncMessage,
  AdalabSyncResponse,
  AdalabTaskInfo,
  AdalabAppState,
  AdalabCommandAction,
  AdalabCommandRequest,
  AdalabCommandResponse,
} from './messages';

export {
  MESSAGE_TYPES,
  isValidMessage,
  isMessageType,
  createMessage,
} from './messages';
